model:
  name: "resnet34_tinyimagenet"
  num_classes: 200

dataset:
  name: "tiny_imagenet"
  data_root: "/home/voz/shared/database/vision/tiny-imagenet-200"
  batch_size: 256
  num_workers: 8
  has_val: false
  split_protocol:
    type: "class_forget"
    forget_classes: [0,1,2,3,4,5,6,7,8,9]

deterministic: true

method:
  name: boundary_shrink
  # FGSM parameters for cross sample generation
  eps: 0.05                  # Noise bound for FGSM
  clamp_min: 0.0             # Min pixel value
  clamp_max: 1.0             # Max pixel value
  
  # Fine-tuning parameters
  ft_epochs: 15               # Decreased from 15: much less fine-tuning
  ft_lr: 0.00001
  ft_momentum: 0.9
  ft_weight_decay: 0.0
  batch_size: 128
  max_norm: 0.0