model:
  name: "resnet34_tinyimagenet"
  num_classes: 200

dataset:
  name: "tiny_imagenet"
  data_root: "/home/voz/shared/database/vision/tiny-imagenet-200"
  batch_size: 256
  num_workers: 8
  has_val: false
  split_protocol:
    type: "class_forget"
    forget_classes: [0,1,2,3,4,5,6,7,8,9]

deterministic: true

method:
  name: fine_tune
  epochs: 10
  lr: 0.001
  weight_decay: 0.0005
  optimizer: adam
  max_norm: 0.0
