model:
  name: "resnet18_cifar"
  num_classes: 10

dataset:
  name: "cifar10"
  data_root: "/home/voz/shared/database/vision"
  batch_size: 256
  num_workers: 8
  has_val: true

  split_protocol:
    type: "class_forget"
    forget_classes: [0]

deterministic: true

method:
  name: boundary_shrink
  # FGSM parameters for cross sample generation
  eps: 0.25                  # Noise bound for FGSM
  clamp_min: 0.0             # Min pixel value
  clamp_max: 1.0             # Max pixel value
  
  # Fine-tuning parameters
  ft_epochs: 10
  ft_lr: 0.00001             # Paper uses 1e-5
  ft_momentum: 0.9
  ft_weight_decay: 0.0
  batch_size: 128
  max_norm: 0.0