model:
  name: "resnet18_cifar"
  num_classes: 10

dataset:
  name: "cifar10"
  data_root: "/home/voz/shared/database/vision"
  batch_size: 256
  num_workers: 8
  has_val: true

  split_protocol:
    type: "class_forget"
    forget_classes: [0]

deterministic: true

method:
  name: fine_tune
  epochs: 10
  lr: 0.001
  weight_decay: 0.0005
  optimizer: adam
  max_norm: 0.0
